apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-app
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services", "namespaces"]
  verbs: ["get", "list", "watch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-rbac
rules:
- apiGroups: [""]
  resources: ["rolebindings.rbac.authorization.k8s.io", "roles.rbac.authorization.k8s.io", "clusterrolebindings.rbac.authorization.k8s.io", "clusterroles.rbac.authorization.k8s.io"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-app
subjects:
- kind: ServiceAccount
  name: controller
  namespace: neuvector
roleRef:
  kind: ClusterRole
  name: neuvector-binding-app
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-rbac
subjects:
- kind: ServiceAccount
  name: controller
  namespace: neuvector
roleRef:
  kind: ClusterRole
  name: neuvector-binding-rbac
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-admission
rules:
- apiGroups: [""]
  resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-admission
subjects:
- kind: ServiceAccount
  name: controller
  namespace: neuvector
roleRef:
  kind: ClusterRole
  name: neuvector-binding-admission
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-customresourcedefinition
rules:
- apiGroups: [""]
  resources: ["customresourcedefinitions"]
  verbs: ["watch", "create", "get", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-customresourcedefinition
subjects:
- kind: ServiceAccount
  name: controller
  namespace: neuvector
roleRef:
  kind: ClusterRole
  name: neuvector-binding-customresourcedefinition
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-nvsecurityrules
rules:
- apiGroups: [""]
  resources: ["nvsecurityrules", "nvclustersecurityrules"]
  verbs: ["get", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-nvadmissioncontrolsecurityrules
rules:
- apiGroups: [""]
  resources: ["nvadmissioncontrolsecurityrules"]
  verbs: ["get", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-nvdlpsecurityrules
rules:
- apiGroups: [""]
  resources: ["nvdlpsecurityrules"]
  verbs: ["get", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-nvwafsecurityrules
rules:
  - apiGroups: [""]
    resources: ["nvwafsecurityrules"]
    verbs: ["get", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-nvsecurityrules
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neuvector-binding-nvsecurityrules
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-nvwafsecurityrules
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neuvector-binding-nvwafsecurityrules
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-nvadmissioncontrolsecurityrules
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neuvector-binding-nvadmissioncontrolsecurityrules
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-nvdlpsecurityrules
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neuvector-binding-nvdlpsecurityrules
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neuvector-binding-scanner
  namespace: neuvector
rules:
  - apiGroups: [""]
    resources: ["deployments"]
    verbs: ["get", "patch", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neuvector-binding-scanner
  namespace: neuvector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: neuvector-binding-scanner
subjects:
  - kind: ServiceAccount
    name: updater
    namespace: neuvector
  - kind: ServiceAccount
    name: controller
    namespace: neuvector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neuvector-binding-secret
  namespace: neuvector
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neuvector-binding-secret
  namespace: neuvector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: neuvector-binding-secret
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-nvcomplianceprofiles
rules:
  - apiGroups: [""]
    resources: ["nvcomplianceprofiles"]
    verbs: ["get", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-nvcomplianceprofiles
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neuvector-binding-nvcomplianceprofiles
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-nvvulnerabilityprofiles
rules:
  - apiGroups: [""]
    resources: ["nvvulnerabilityprofiles"]
    verbs: ["get", "list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-nvvulnerabilityprofiles
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neuvector-binding-nvvulnerabilityprofiles
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector

