apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-app
rules:
  - verbs:
      - get
      - list
      - watch
      - update
    resources:
      - nodes
      - pods
      - services
      - namespaces

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-rbac
rules:
  - verbs:
      - get
      - list
      - watch
    resources:
      - rolebindings.rbac.authorization.k8s.io
      - roles.rbac.authorization.k8s.io
      - clusterrolebindings.rbac.authorization.k8s.io
      - clusterroles.rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-app
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector
roleRef:
  kind: ClusterRole
  name: neuvector-binding-app
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-rbac
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector
roleRef:
  kind: ClusterRole
  name: neuvector-binding-rbac
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-admission
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-admission
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector
roleRef:
  kind: ClusterRole
  name: neuvector-binding-admission
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-customresourcedefinition
rules:
  - verbs:
      - watch
      - create
      - get
      - update
    resources:
      - customresourcedefinitions

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-customresourcedefinition
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector
roleRef:
  kind: ClusterRole
  name: neuvector-binding-customresourcedefinition
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-nvsecurityrules
rules:
  - verbs:
      - get
      - list
      - delete
    resources:
      - nvsecurityrules
      - nvclustersecurityrules

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-nvadmissioncontrolsecurityrules
rules:
  - verbs:
      - get
      - list
      - delete
    resources:
      - nvadmissioncontrolsecurityrules

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-nvdlpsecurityrules
rules:
  - verbs:
      - get
      - list
      - delete
    resources:
      - nvdlpsecurityrules

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-nvwafsecurityrules
rules:
  - verbs:
      - get
      - list
      - delete
    resources:
      - nvwafsecurityrules

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-nvsecurityrules
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector
roleRef:
  kind: ClusterRole
  name: neuvector-binding-nvsecurityrules
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-view
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-nvwafsecurityrules
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector
roleRef:
  kind: ClusterRole
  name: neuvector-binding-nvwafsecurityrules
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-nvadmissioncontrolsecurityrules
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector
roleRef:
  kind: ClusterRole
  name: neuvector-binding-nvadmissioncontrolsecurityrules
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-nvdlpsecurityrules
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector
roleRef:
  kind: ClusterRole
  name: neuvector-binding-nvdlpsecurityrules
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neuvector-binding-scanner
  namespace: neuvector
rules:
  - verbs:
      - get
      - patch
      - update
      - watch
    resources:
      - deployments

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neuvector-binding-scanner
  namespace: neuvector
subjects:
  - kind: ServiceAccount
    name: updater
    namespace: neuvector
  - kind: ServiceAccount
    name: controller
    namespace: neuvector
roleRef:
  kind: Role
  name: neuvector-binding-scanner
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neuvector-binding-secret
  namespace: neuvector
rules:
  - verbs:
      - get
    resources:
      - secrets

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neuvector-binding-secret
  namespace: neuvector
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector
roleRef:
  kind: Role
  name: neuvector-binding-secret
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-nvcomplianceprofiles
rules:
  - verbs:
      - get
      - list
      - delete
    resources:
      - nvcomplianceprofiles

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-nvcomplianceprofiles
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector
roleRef:
  kind: ClusterRole
  name: neuvector-binding-nvcomplianceprofiles
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-nvvulnerabilityprofiles
rules:
  - verbs:
      - get
      - list
      - delete
    resources:
      - nvvulnerabilityprofiles

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-nvvulnerabilityprofiles
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: neuvector
roleRef:
  kind: ClusterRole
  name: neuvector-binding-nvvulnerabilityprofiles
  apiGroup: rbac.authorization.k8s.io
